<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-05T07:42:48 IST" name="Suite" finished-at="2024-02-05T07:43:07 IST" duration-ms="18676">
    <groups>
      <group name="Master">
        <method signature="Tc002LoginTest.test_login()[pri:0, instance:testcases.Tc002LoginTest@2d1ef81a]" name="test_login" class="testcases.Tc002LoginTest"/>
      </group> <!-- Master -->
      <group name="Sanity">
        <method signature="Tc002LoginTest.test_login()[pri:0, instance:testcases.Tc002LoginTest@2d1ef81a]" name="test_login" class="testcases.Tc002LoginTest"/>
      </group> <!-- Sanity -->
    </groups>
    <test started-at="2024-02-05T07:42:48 IST" name="Test" finished-at="2024-02-05T07:43:07 IST" duration-ms="18676">
      <class name="testcases.Tc002LoginTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testcases.Tc002LoginTest@2d1ef81a]" started-at="2024-02-05T07:42:49 IST" name="setup" finished-at="2024-02-05T07:42:55 IST" duration-ms="6655" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test_login()[pri:0, instance:testcases.Tc002LoginTest@2d1ef81a]" started-at="2024-02-05T07:42:55 IST" name="test_login" finished-at="2024-02-05T07:43:06 IST" duration-ms="11241" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at testcases.Tc002LoginTest.test_login(Tc002LoginTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.Tc002LoginTest@2d1ef81a]" started-at="2024-02-05T07:43:07 IST" name="tearDown" finished-at="2024-02-05T07:43:07 IST" duration-ms="275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.Tc002LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
